### ISSUE TITLE
AttributeError: 'DenseNet' object has no attribute 'features2'

### ISSUE THREAD

**Issue by ankamdeepika** [mlmed/covid-severity#2]
C:\Users\Dell\Desktop>python predict.py test.jpg
Traceback (most recent call last):
  File "predict.py", line 150, in <module>
    outputs = process(model, cfg.img_path, cfg.cuda)
  File "predict.py", line 116, in process
    outputs = model(img)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "predict.py", line 81, in forward
    ret["feats"] = self.basemodel.features2(x)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'DenseNet' object has no attribute 'features2'

please help me with this error

**Comment by ieee8023** [comment]
Make sure you are using the latest version of torchxrayvision. Run `pip install torchxrayvision --upgrade`

**Comment by ankamdeepika** [comment]
Thank you so  much. It worked.
